/**
 * Application-level error codes used in API responses.
 * Provides stable, machine-readable error identifiers.
 */
export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Auth
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // Groups
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  NOT_A_MEMBER = 'NOT_A_MEMBER',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
  INVITATION_MAX_USES_REACHED = 'INVITATION_MAX_USES_REACHED',
  ALREADY_A_MEMBER = 'ALREADY_A_MEMBER',
  CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER',
  CANNOT_LEAVE_AS_SOLE_OWNER = 'CANNOT_LEAVE_AS_SOLE_OWNER',

  // Sport Profiles & Checklists
  SPORT_PROFILE_NOT_FOUND = 'SPORT_PROFILE_NOT_FOUND',
  NOT_PROFILE_OWNER = 'NOT_PROFILE_OWNER',
  CHECKLIST_NOT_FOUND = 'CHECKLIST_NOT_FOUND',
  NOT_CHECKLIST_OWNER = 'NOT_CHECKLIST_OWNER',
  EQUIPMENT_ITEM_NOT_FOUND = 'EQUIPMENT_ITEM_NOT_FOUND',
}

export class AppError extends Error {
  constructor(
    public readonly code: AppErrorCode,
    message: string,
    public readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = 'AppError';
  }
}
