/**
 * Application-level error codes used in API responses.
 * Provides stable, machine-readable error identifiers.
 */
export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Auth
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // Groups
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  NOT_A_MEMBER = 'NOT_A_MEMBER',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
  INVITATION_MAX_USES_REACHED = 'INVITATION_MAX_USES_REACHED',
  ALREADY_A_MEMBER = 'ALREADY_A_MEMBER',
  CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER',
  CANNOT_LEAVE_AS_SOLE_OWNER = 'CANNOT_LEAVE_AS_SOLE_OWNER',

  // Sport Profiles & Checklists
  SPORT_PROFILE_NOT_FOUND = 'SPORT_PROFILE_NOT_FOUND',
  NOT_PROFILE_OWNER = 'NOT_PROFILE_OWNER',
  CHECKLIST_NOT_FOUND = 'CHECKLIST_NOT_FOUND',
  NOT_CHECKLIST_OWNER = 'NOT_CHECKLIST_OWNER',
  EQUIPMENT_ITEM_NOT_FOUND = 'EQUIPMENT_ITEM_NOT_FOUND',

  // Shared Equipment
  ACTIVITY_NOT_FOUND = 'ACTIVITY_NOT_FOUND',
  SHARED_ITEM_NOT_FOUND = 'SHARED_ITEM_NOT_FOUND',
  SHARED_ITEM_ALREADY_COVERED = 'SHARED_ITEM_ALREADY_COVERED',
  ALREADY_CLAIMED = 'ALREADY_CLAIMED',
  RESPONSIBILITY_NOT_FOUND = 'RESPONSIBILITY_NOT_FOUND',
  CANNOT_RELEASE_PACKED = 'CANNOT_RELEASE_PACKED',
  CANNOT_TAKE_OVER_COVERED = 'CANNOT_TAKE_OVER_COVERED',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  TRANSFER_TARGET_NOT_MEMBER = 'TRANSFER_TARGET_NOT_MEMBER',

  // Packing Sessions
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ALREADY_COMPLETED = 'SESSION_ALREADY_COMPLETED',
  MANDATORY_ITEMS_UNRESOLVED = 'MANDATORY_ITEMS_UNRESOLVED',
  DECISION_ALREADY_MADE = 'DECISION_ALREADY_MADE',
  INVALID_DECISION_REASON = 'INVALID_DECISION_REASON',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
}

export class AppError extends Error {
  constructor(
    public readonly code: AppErrorCode,
    message: string,
    public readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = 'AppError';
  }
}
